# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: render_page.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11render_page.proto\x12\x0brender_page\"\x1d\n\rRenderRequest\x12\x0c\n\x04html\x18\x01 \x01(\t\"\x1a\n\x0bRenderReply\x12\x0b\n\x03pdf\x18\x01 \x01(\x0c\x32Q\n\nRenderPage\x12\x43\n\tRenderPDF\x12\x1a.render_page.RenderRequest\x1a\x18.render_page.RenderReply\"\x00\x42\x36\n\x1bio.grpc.examples.helloworldB\x0fHelloWorldProtoP\x01\xa2\x02\x03HLWb\x06proto3')



_RENDERREQUEST = DESCRIPTOR.message_types_by_name['RenderRequest']
_RENDERREPLY = DESCRIPTOR.message_types_by_name['RenderReply']
RenderRequest = _reflection.GeneratedProtocolMessageType('RenderRequest', (_message.Message,), {
  'DESCRIPTOR' : _RENDERREQUEST,
  '__module__' : 'render_page_pb2'
  # @@protoc_insertion_point(class_scope:render_page.RenderRequest)
  })
_sym_db.RegisterMessage(RenderRequest)

RenderReply = _reflection.GeneratedProtocolMessageType('RenderReply', (_message.Message,), {
  'DESCRIPTOR' : _RENDERREPLY,
  '__module__' : 'render_page_pb2'
  # @@protoc_insertion_point(class_scope:render_page.RenderReply)
  })
_sym_db.RegisterMessage(RenderReply)

_RENDERPAGE = DESCRIPTOR.services_by_name['RenderPage']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\033io.grpc.examples.helloworldB\017HelloWorldProtoP\001\242\002\003HLW'
  _RENDERREQUEST._serialized_start=34
  _RENDERREQUEST._serialized_end=63
  _RENDERREPLY._serialized_start=65
  _RENDERREPLY._serialized_end=91
  _RENDERPAGE._serialized_start=93
  _RENDERPAGE._serialized_end=174
# @@protoc_insertion_point(module_scope)
