# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import render_page_pb2 as render__page__pb2


class RenderPageStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RenderPDF = channel.unary_unary(
                '/render_page.RenderPage/RenderPDF',
                request_serializer=render__page__pb2.RenderRequest.SerializeToString,
                response_deserializer=render__page__pb2.RenderReply.FromString,
                )


class RenderPageServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RenderPDF(self, request, context):
        """Renders a HTML page into PDF
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RenderPageServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RenderPDF': grpc.unary_unary_rpc_method_handler(
                    servicer.RenderPDF,
                    request_deserializer=render__page__pb2.RenderRequest.FromString,
                    response_serializer=render__page__pb2.RenderReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'render_page.RenderPage', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RenderPage(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RenderPDF(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/render_page.RenderPage/RenderPDF',
            render__page__pb2.RenderRequest.SerializeToString,
            render__page__pb2.RenderReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
