kind: Deployment
apiVersion: apps/v1
metadata:
  name: render-page
  namespace: worker-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: render-page
  template:
    metadata:
      labels:
        app: render-page
    spec:
      imagePullSecrets:
      - name: ghcr-pull-secret
      containers:
        - name: render-page
          image: ghcr.io/haninge-digit/digit-service-render_page:main
          imagePullPolicy: Always
          ports:
            - name: gRPC
              containerPort: 50051
              protocol: TCP
          env:
            - name: DEBUG
              value: 'false'
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
          # livenessProbe:
          #   httpGet:
          #     path: /probe/liveness
          #     port: http
          #     scheme: HTTP
          #   timeoutSeconds: 1
          #   periodSeconds: 10
          #   successThreshold: 1
          #   failureThreshold: 3
          # readinessProbe:
          #   httpGet:
          #     path: /probe/readiness
          #     port: http
          #     scheme: HTTP
          #   initialDelaySeconds: 2
          #   timeoutSeconds: 10
          #   periodSeconds: 10
          #   successThreshold: 1
          #   failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          securityContext: {}
      tolerations:
      - key: "kubernetes.azure.com/scalesetpriority"
        operator: "Equal"
        value: "spot"
        effect: "NoSchedule"
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
---
kind: Service
apiVersion: v1
metadata:
  name: render-page
  namespace: worker-services
spec:
  ports:
    - name: gRPC
      protocol: TCP
      port: 50051
      targetPort: 50051
  selector:
    app: render-page
  type: ClusterIP
